title: "တပ်ကုန်းမြို့နယ် သမိုင်းနှင့်ရုပ်ပုံလွှာ"
description: "နေပြည်တော်၊ တပ်ကုန်းမြို့နယ်၏ ဒေသသမိုင်းနှင့်ယဉ်ကျေးမှု၊ မှတ်တမ်းမှတ်ရာနှင့်အချက်အလက်များကို စုစည်းထိန်းသိမ်းထားသည့် <br> ဒီဂျစ်တယ်မော်ကွန်းတိုက်"
show_downloads: false
github_button: false
theme: jekyll-theme-cayman
<div style="width: 100%; margin-top: 50px; margin-bottom: 20px; overflow: hidden; border-radius: 6px; box-shadow: 0 4px 10px rgba(0,0,0,0.08);">
  <img src="./assets/images/tatkon-sat-image.png" alt="တပ်ကုန်းမြို့ မြင်ကွင်းကျယ်" style="width: 100%; height: auto; display: block; object-fit: contain;">
</div>
