title: "ကိုယ့်မြို့အမည် မော်ကွန်းတိုက်"
description: "ကျွန်ုပ်တို့၏ ဒေသသမိုင်း၊ ယဉ်ကျေးမှုနှင့် အမှတ်တရများကို ရေရှည်ထိန်းရှိမ်းရန် စုစည်းထားသော နေရာ"
show_downloads: false

# ဒီစာကြောင်းလေးကို ထပ်တိုးပေးပါဗျာ (View on GitHub ခလုတ်ကို ပိတ်တာပါ)
github_button: false

theme: jekyll-theme-cayman
